
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Ajusta según lo que necesites
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        ports:
        - containerPort: 8081  # Puerto por defecto de Nexus Repository
        env:
        - name: NEXUS_SECURITY_RANDOMPASSWORD
          value: "true"  # Desactivar la contraseña aleatoria al inicio
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data  # Persistencia de datos
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc  # Usaremos un PVC para persistir los datos
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30082
  type: NodePort