---
apiVersion: v1
kind: Namespace
metadata:
  name: jmpg-developer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: jmpg-developer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: artifactory.jmpg.dev/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.database.svc.cluster.local:5432/backend
            - name: SPRING_DATASOURCE_USERNAME
              value: ps_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: SecurePassword
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jmpg-developer
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080