---
apiVersion: v1
kind: Namespace
metadata:
  name: jmpg-developer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: jmpg-developer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jmpgdeveloper/frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: jmpg-developer
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80