apiVersion: v1
kind: Namespace
metadata:
  name: confluent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:8.0.0
        ports:
          - containerPort: 9092
          - containerPort: 9093
        env:
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_BROKERS
          value: broker.confluent.svc.cluster.local:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper.confluent.svc.cluster.local:2181'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker.confluent.svc.cluster.local:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_BROKER_ID
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: confluent
spec:
  selector:
    app: broker
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
    nodePort: 30092
  type: NodePort