apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Ajusta según tus necesidades
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0  # Versión 7.10, ajusta según la que desees
        env:
        - name: discovery.type
          value: single-node  # Para usar Elasticsearch en un solo nodo (configuración básica)
        - name: ES_JAVA_OPTS
          value: "-Xmx512m -Xms512m"  # Opcional: Limita el uso de memoria de Java
        ports:
        - containerPort: 9200  # Puerto de Elasticsearch
        - containerPort: 9300  # Puerto de comunicación entre nodos (si usas más de 1 réplica)
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data  # Directorio para almacenar los datos
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-pvc  # Volumen persistente para almacenar los datos
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
      nodePort: 30000  # Define un puerto accesible desde fuera del clúster
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: transport
  selector:
    app: elasticsearch
  type: NodePort  # Expondrá Elasticsearch en todos los nodos