apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_PASSWORD
              value: sonar
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: database-data
          persistentVolumeClaim:
            claimName: database-pvc