apiVersion: v1
kind: Namespace
metadata:
  name: confluent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: confluentinc/cp-enterprise-control-center:7.9.1
        ports:
        - containerPort: 9021
        env:
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: broker.confluent.svc.cluster.local:9092
        - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
          value: http://schema-registry.confluent.svc.cluster.local:8081
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
          value: "1"
        - name: CONFLUENT_METRICS_TOPIC_REPLICATION
          value: "1"
        - name: PORT
          value: "9021"
---
apiVersion: v1
kind: Service
metadata:
  name: control-center
  namespace: confluent
spec:
  selector:
    app: control-center
  ports:
  - protocol: TCP
    port: 9021
    targetPort: 9021
    nodePort: 30021
  type: NodePort