apiVersion: v1
kind: Namespace
metadata:
  name: confluent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:7.9.1
        ports:
        - containerPort: 8081
        # command: ["sleep"]
        # args: ["3600"]
        env:
        - name: BOOTSTRAP_SERVERS
          value: broker.confluent.svc.cluster.local:9092
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: ""
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: PLAINTEXT://broker.confluent.svc.cluster.local:9092
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry.confluent.svc.cluster.local
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: confluent
spec:
  selector:
    app: schema-registry
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
  type: NodePort