
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Ajusta según lo que necesites
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        resources:
          limits:
            memory: "4Gi"
            cpu: "1000m"
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8081  # Puerto por defecto de Nexus Repository
        volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc  # Usaremos un PVC para persistir los datos
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: artifactory
spec:
  selector:
    app: nexus
  ports:
    - name: nexus-http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30082
    - name: nexus-repository
      protocol: TCP
      port: 32000
      targetPort: 32000
      nodePort: 32000
  type: NodePort