
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        resources:
          limits:
            memory: "4Gi"
            cpu: "1000m"
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - name: nexus-http
          containerPort: 8081
        - name: docker-http
          containerPort: 5000
        env:
        - name: DATABASE_TYPE
          value: postgresql
        - name: DATABASE_HOST
          value: postgres.database.svc.cluster.local
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: nexus
        - name: DATABASE_USER
          value: nexus_user
        - name: DATABASE_PASSWORD
          value: nexus_password
        # - name: NEXUS_SECURITY_RANDOMPASSWORD
        #   value: "false"
        # - name: NEXUS_SECURITY_INITIALPASSWORD
        #   value: "@*Tf@0nq!aDw#6UEbWjN"
        volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: artifactory
spec:
  type: ClusterIP
  selector:
    app: nexus
  ports:
    - name: docker-http
      port: 5000
      targetPort: 5000
    - name: nexus-http
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: artifactory
spec:
  ingressClassName: traefik
  rules:
    - host: artifactory.gaming-guild.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 8081