---
apiVersion: v1
kind: Namespace
metadata:
  name: gaming-guild-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: gaming-guild-ns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: gaming-guild-app
  template:
    metadata:
      labels:
        app: gaming-guild-app
    spec:
      containers:
        - name: gaming-guild
          image: artifactory.jmpg.dev/jmpg-developer/backend-native:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.database.svc.cluster.local:5432/backend
            - name: SPRING_DATASOURCE_USERNAME
              value: ps_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: SecurePassword
---
apiVersion: v1
kind: Service
metadata:
  name: gaming-guild-service
  namespace: gaming-guild-ns
spec:
  type: ClusterIP
  selector:
    app: gaming-guild-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080