apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: apache/kafka:latest
        ports:
          - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: kafka
spec:
  selector:
    app: broker
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
  type: ClusterIP
---  