apiVersion: apps/v1
kind: Deployment
metadata:
  name: kowl
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kowl
  template:
    metadata:
      labels:
        app: kowl
    spec:
      containers:
      - name: kowl
        image: quay.io/cloudhut/kowl:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKERS
          value: kafka.kafka.svc.cluster.local:9092
        - name: SCHEMA_REGISTRY_URL
          value: "http://apicurio-registry.kafka.svc.cluster.local:8080"
        - name: KAFKA_TLS_ENABLED
          value: "false"
        - name: KAFKA_SASL_ENABLED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: kowl
  namespace: kafka
spec:
  selector:
    app: kowl
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30070
  type: NodePort
