apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
      - name: apicurio-registry
        image: apicurio/apicurio-registry:3.0.6
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka.kafka.svc.cluster.local:9092
        - name: REGISTRY_STORAGE
          value: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry
  namespace: kafka
spec:
  selector:
    app: apicurio-registry
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081
  type: NodePort