apiVersion: v1
kind: Namespace
metadata:
  name: confluent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.9.0
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper/data
        - name: logs
          mountPath: /var/lib/zookeeper/log
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      volumes:
      - name: data
        emptyDir: {}
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: confluent
spec:
  selector:
    app: zookeeper
  ports:
  - name: client
    port: 2181
    targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-server:7.9.0
        ports:
        - containerPort: 9092
        - containerPort: 9101
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
        - name: KAFKA_METRIC_REPORTERS
          value: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_JMX_PORT
          value: "9101"
        - name: KAFKA_JMX_HOSTNAME
          value: "localhost"
        - name: KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
          value: "http://schemaregistry:8081"
        - name: CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS
          value: "1"
        - name: CONFLUENT_METRICS_ENABLE
          value: "true"
        - name: CONFLUENT_SUPPORT_CUSTOMER_ID
          value: "anonymous"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka/data
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: confluent
spec:
  selector:
    app: kafka
  ports:
  - name: kafka
    port: 29092
    targetPort: 29092
  - name: kafka-external
    port: 9092
    targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schemaregistry
  template:
    metadata:
      labels:
        app: schemaregistry
    spec:
      containers:
      - name: schemaregistry
        image: confluentinc/cp-schema-registry:7.9.0
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schemaregistry"
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: "http://0.0.0.0:8081"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  selector:
    app: schemaregistry
  ports:
  - name: http
    port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
      - name: connect
        image: confluentinc/cp-server-connect:7.9.0
        ports:
        - containerPort: 8083
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "connect"
        - name: CONNECT_GROUP_ID
          value: "compose-connect-group"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "docker-connect-configs"
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_OFFSET_FLUSH_INTERVAL_MS
          value: "10000"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "docker-connect-offsets"
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "docker-connect-status"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.storage.StringConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "io.confluent.connect.avro.AvroConverter"
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://schemaregistry:8081"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java,/usr/share/confluent-hub-components"
        - name: CONNECT_LOG4J_LOGGERS
          value: "org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8083
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 500
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: connect
  namespace: confluent
spec:
  selector:
    app: connect
  ports:
  - name: http
    port: 8083
    targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb
  template:
    metadata:
      labels:
        app: ksqldb
    spec:
      containers:
      - name: ksqldb
        image: confluentinc/cp-ksqldb-server:7.9.0
        ports:
        - containerPort: 8088
        env:
        - name: KSQL_CONFIG_DIR
          value: "/etc/ksql"
        - name: KSQL_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: KSQL_HOST_NAME
          value: "ksqldb"
        - name: KSQL_LISTENERS
          value: "http://0.0.0.0:8088"
        - name: KSQL_CACHE_MAX_BYTES_BUFFERING
          value: "0"
        - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
          value: "http://schemaregistry:8081"
        - name: KSQL_PRODUCER_INTERCEPTOR_CLASSES
          value: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
        - name: KSQL_CONSUMER_INTERCEPTOR_CLASSES
          value: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
        - name: KSQL_KSQL_CONNECT_URL
          value: "http://connect:8083"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /info
            port: 8088
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 500
        volumeMounts:
        - name: data
          mountPath: /var/lib/ksqldb
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ksqldb
  namespace: confluent
spec:
  selector:
    app: ksqldb
  ports:
  - name: http
    port: 8088
    targetPort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlcenter
  template:
    metadata:
      labels:
        app: controlcenter
    spec:
      containers:
      - name: controlcenter
        image: confluentinc/cp-enterprise-control-center:7.9.0
        ports:
        - containerPort: 9021
        env:
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER
          value: "connect:8083"
        - name: CONTROL_CENTER_KSQL_KSQLDB1_URL
          value: "http://ksqldb:8088"
        - name: CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL
          value: "http://localhost:8088"
        - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
          value: "http://schemaregistry:8081"
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
          value: "1"
        - name: CONFLUENT_METRICS_TOPIC_REPLICATION
          value: "1"
        - name: PORT
          value: "9021"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 9021
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 500
        volumeMounts:
        - name: data
          mountPath: /var/lib/confluent-control-center
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: controlcenter
  namespace: confluent
spec:
  selector:
    app: controlcenter
  type: LoadBalancer
  ports:
  - name: http
    port: 9021
    targetPort: 9021
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkarestproxy
  template:
    metadata:
      labels:
        app: kafkarestproxy
    spec:
      containers:
      - name: kafkarestproxy
        image: confluentinc/cp-kafka-rest:7.9.0
        ports:
        - containerPort: 8082
        env:
        - name: KAFKA_REST_HOST_NAME
          value: "kafkarestproxy"
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: KAFKA_REST_LISTENERS
          value: "http://0.0.0.0:8082"
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: "http://schemaregistry:8081"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  selector:
    app: kafkarestproxy
  ports:
  - name: http
    port: 8082
    targetPort: 8082